### ISSUE TITLE
WIP/WebAdminHTML .* - Spaces not set correctly

### ISSUE THREAD

**Issue by JanUrbansky** [NeonKnightOA/unreal-localization#23]
Ok...I think there is an issue in general in all the generated files. Check out all the WIP -> WebAdminHTML files. The HTML code at all the lines cannot work, if you see where the problem is.

**Right:**
`; EN: Web3=<frame src="/MainLinksPage" name="menu" noresize frameborder="0" marginheight="0" scrolling="no" framespacing="0">`

**Wrong:**
`Web3=<frame src="/ MainLinksPage "name =" menu "noresize frameborder =" 0 "marginheight =" 0 "scrolling =" no "framepacing =" 0">`

**Comment by NeonKnightOA** [comment]
That's why they're low priority for now. They are quite difficult and annoying to handle.

**Comment by NeonKnightOA** [comment]
Buggie was taking care of the Webadmin side of Unreal. I'll wait before doing any changes to WebAdminHTML.*.

**Comment by NeonKnightOA** [comment]
In the end I've decided to keep both WebAdminHTML and ScriptedAI untranslated. I was advised to not translate development tools for ScriptedAI, and as for WebAdminHTML it's TOO difficult to maintain. Once the localizable strings have been stripped from the rest of the code then we can properly localize WebAdminHTML.
