### ISSUE TITLE
EZ to read interface on that lovely patch469c! \o/

### ISSUE THREAD

**Issue by VirgileVILE** [NeonKnightOA/unreal-localization#71]
Love the idea of overlaying the French text over the options.
https://i.imgur.com/SZHBZGI.png

**Comment by NeonKnightOA** [comment]
Any suggestions on how those lines could be resumed/fixed?

**Comment by VirgileVILE** [comment]
By removing the patch?

**Comment by VirgileVILE** [comment]
More seriously, if the bug does not exist on patch 469b, who better than the culprit who produced patch 469c to give the answer?

**Comment by NeonKnightOA** [comment]
I've asked for help and got non-constructive snark. Closing.

**Comment by VirgileVILE** [comment]
I dont speak ingliche
