### ISSUE TITLE
Unending quote in template

### ISSUE THREAD

**Issue by LDinos** [NeonKnightOA/unreal-localization#73]
Just to let you know UnrealTournament\WIP\Template\UMenu line 353 has an unending quote, in case anyone forgets to put it!

**Comment by NeonKnightOA** [comment]
I gotta check that one out...

**Comment by NeonKnightOA** [comment]
Hmmm... can you provide an example? I fail to see where the problem in UMenu lies...

**Comment by LDinos** [comment]
https://github.com/NeonKnightOA/unreal-localization/blob/master/UnrealTournament/WIP/Template/UMenu.template
The problem is shown in the screenshot here: https://imgur.com/a/oIhCRWG
There is only one single quote that doesn't close :)
